"""
PyMOL Visualization Generator for Protein-Ligand Interactions.

This module generates PyMOL scripts (.pml) showing all detected
interactions with distance labels.

Supports multi-ligand analysis with toggleable groups per ligand.
"""

import os
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any

from .parser import Interaction
from .constants import INTERACTION_COLORS

# ============================================================================
# DASH SETTINGS
# ============================================================================
# PyMOL dash settings (gap, length) to match 2D diagram line styles
# Solid lines: gap=0, length=0.5
# Dashed lines: gap>0, length>0 (smaller gap = more dense dashes)

INTERACTION_DASH = {
    # SOLID lines (to match 2D diagram)
    'Hydrogen Bonds': (0, 0.5),      # Solid
    'Salt Bridges': (0, 0.5),        # Solid
    'π-π Stacking': (0, 0.5),        # Solid
    'Cation-π': (0, 0.5),            # Solid
    'π-Cation': (0, 0.5),            # Solid
    'Metal Coordination': (0, 0.5),  # Solid
    # DASHED lines (to match 2D diagram)
    'Hydrophobic': (0.15, 0.20),     # Dashed
    'Halogen Bonds': (0.15, 0.20),   # Dashed
    'Water Bridges': (0.15, 0.20),     # Dashed
    'XWH Bridges': (0.15, 0.20),       # Dashed
}

# Metal-specific colors for visualization
METAL_COLORS = {
    'CU': 'orange',
    'NA': 'lightblue',
    'FE': 'grey50',
    'FE2': 'grey50',
    'FE3': 'grey50',
    'ZN': 'slate',
    'MG': 'lime',
    'CA': 'tv_yellow',
    'MN': 'violet',
    'CO': 'salmon',
    'NI': 'palegreen',
}

# NOTE: We always use OR-fallback for ligand selections in PyMOL.
# When has_chains=True but the ligand has a blank chain in the actual PDB file
# (common in docking), "chain X and resn ..." would fail. The OR-fallback
# "(chain X and resn ...) or (resn ...)" is safe in all cases.


# ============================================================================
# SCRIPT GENERATION
# ============================================================================

def generate_pymol_script(pdb_file: str, 
                          results: Dict,
                          ligand_name: str = None,
                          output_pse: str = "interactions.pse",
                          ligand_info: dict = None,
                          portable: bool = False) -> str:
    """
    Generate PyMOL script to visualize interactions.
    
    Args:
        pdb_file: Path to PDB file
        results: Dictionary of interactions (can be multi-ligand or single-ligand format)
        ligand_name: Optional ligand residue name
        output_pse: Output session file path
        ligand_info: Optional dictionary with ligand residue info
        portable: If True, use only filenames (not full paths) for portability.
                  This allows users to download PML and PDB together and run locally.
        
    Returns:
        PyMOL script as string
    """
    if portable:
        # Use only filenames for portability (no server paths exposed)
        pdb_path_for_script = os.path.basename(pdb_file)
        pse_path_for_script = os.path.basename(output_pse)
    else:
        # Use absolute paths for local CLI usage
        pdb_path_for_script = os.path.abspath(pdb_file)
        pse_path_for_script = os.path.abspath(output_pse)
    
    lines = []
    
    # Header
    lines.extend([
        "# PyMOL Visualization Script",
        "# Generated by NCI-Profiler - Non-Covalent Interaction Profiler",
        "",
        f"load {pdb_path_for_script}, complex",
        "",
        "# Display settings",
        "bg_color white",
        "set depth_cue, 0",
        "set ray_shadows, 0",
        "set antialias, 2",
        "set cartoon_fancy_helices, 0",
        "set cartoon_highlight_color, grey40",
        "set light_count, 5",
        "",
        "# Protein",
        "hide everything, complex",
        "select protein, complex and polymer.protein",
        "show cartoon, protein",
        "color grey80, protein",
        "set cartoon_transparency, 0.3, protein",
        "",
        "hide everything, resn HOH+WAT",
        "",
    ])
    
    # Detect format: multi-ligand or single-ligand
    is_multi_ligand = False
    if results and isinstance(list(results.values())[0], dict):
        if 'results' in list(results.values())[0]:
            is_multi_ligand = True
    
    if is_multi_ligand:
        lines.extend(_generate_multi_ligand_script(results))
    else:
        lines.extend(_generate_single_ligand_script(results, ligand_name, ligand_info))
    
    # Final settings
    lines.extend([
        "",
        "# Final settings",
        "show dashes",
        "set dash_round_ends, 1",
        "center" if is_multi_ligand else "center ligand",
        "zoom center, 15",
        "",
        f"save {pse_path_for_script}",
        "print('PyMOL session created!')",
    ])
    
    return '\n'.join(lines)


def _generate_multi_ligand_script(results: Dict) -> List[str]:
    """Generate script lines for multi-ligand results."""
    lines = []
    ligand_groups = []
    
    for ligand_id, ligand_data in results.items():
        if ligand_data.get('is_metal', False):
            continue  # Handle metals separately
            
        ligand_results = ligand_data['results']
        lig_chain, lig_resname, lig_resnum = ligand_data['residue_info']
        lig_has_chains = ligand_data.get('has_chains', False)
        
        safe_id = ligand_id.replace(':', '_').replace('-', '_')
        ligand_groups.append(safe_id)
        
        lines.append(f"\n# ========== LIGAND: {ligand_id} ==========")
        
        # LIGAND SELECTION:
        # Always use OR-fallback when has_chains=True: try with chain first,
        # then without. This handles docked ligands with blank chain IDs
        # regardless of the ligand residue name.
        if lig_has_chains and lig_chain:
            lig_sel_with_chain = f"chain {lig_chain} and resn {lig_resname} and resi {lig_resnum}"
            lig_sel_without_chain = f"resn {lig_resname} and resi {lig_resnum}"
            lig_sel = f"({lig_sel_with_chain}) or ({lig_sel_without_chain})"
        else:
            lig_sel = f"resn {lig_resname} and resi {lig_resnum}"
        
        lines.extend([
            f"select {safe_id}_lig, {lig_sel}",
            f"show sticks, {safe_id}_lig",
            f"show spheres, {safe_id}_lig",
            f"set sphere_scale, 0.25, {safe_id}_lig",
            f"set sphere_transparency, 0.4, {safe_id}_lig",
            f"util.cbag {safe_id}_lig",
            "",
        ])
        
        # Collect and show interacting residues
        all_residues = set()
        for itype, interactions in ligand_results.items():
            for inter in interactions:
                all_residues.add(inter.protein_residue)
        
        if all_residues:
            lines.append(f"select {safe_id}_res, none")
            for res_id in all_residues:
                sel = _residue_selection(res_id, lig_has_chains)
                lines.append(f"select {safe_id}_res, {safe_id}_res or ({sel})")
            
            lines.extend([
                f"select {safe_id}_res, {safe_id}_res and not {safe_id}_lig",
                f"show sticks, {safe_id}_res",
                f"set stick_radius, 0.2, {safe_id}_res",
                f"color cyan, {safe_id}_res and elem C",
                f"label {safe_id}_res and name CA, resn + resi",
                f"set label_size, 18, {safe_id}_res",
                f"set label_font_id, 7, {safe_id}_res",
                f"set label_color, black, {safe_id}_res",
                "",
            ])
        
        # Generate interaction visualizations
        lines.extend(_generate_interaction_lines(ligand_results, safe_id, lig_has_chains))
        
        # Group all objects for this ligand
        lines.extend([
            f"group {safe_id}, {safe_id}_*",
            f"enable {safe_id}",
            "",
        ])
    
    # Summary comment
    if ligand_groups:
        lines.append(f"# Toggleable ligand groups: {', '.join(ligand_groups)}")
    
    return lines


def _generate_single_ligand_script(results: Dict, 
                                   ligand_name: str,
                                   ligand_info: dict) -> List[str]:
    """Generate script lines for single-ligand results."""
    lines = []
    
    # Build ligand selection
    has_chains = False
    if ligand_info and ligand_info.get('residues'):
        residues = ligand_info['residues']
        has_chains = ligand_info.get('has_chains', False)
        if len(residues) == 1:
            chain, resname, resnum = residues[0]
            if has_chains:
                sel_with = f"chain {chain} and resn {resname} and resi {resnum}"
                sel_without = f"resn {resname} and resi {resnum}"
                lines.append(f"select ligand, ({sel_with}) or ({sel_without})")
            else:
                lines.append(f"select ligand, resn {resname} and resi {resnum}")
        else:
            lines.append("select ligand, none")
            for chain, resname, resnum in residues:
                if has_chains:
                    sel_with = f"chain {chain} and resn {resname} and resi {resnum}"
                    sel_without = f"resn {resname} and resi {resnum}"
                    lines.append(f"select ligand, ligand or (({sel_with}) or ({sel_without}))")
                else:
                    lines.append(f"select ligand, ligand or (resn {resname} and resi {resnum})")
    elif ligand_name:
        lines.append(f"select ligand, resn {ligand_name}")
    else:
        lines.append("select ligand, organic and not resn HOH+WAT")
    
    lines.extend([
        "show sticks, ligand",
        "show spheres, ligand",
        "set sphere_scale, 0.25, ligand",
        "set sphere_transparency, 0.4, ligand",
        "util.cbag ligand",
        "",
    ])
    
    # Collect interacting residues
    all_residues = set()
    for itype, interactions in results.items():
        for inter in interactions:
            all_residues.add(inter.protein_residue)
    
    if all_residues:
        lines.append("select interacting_residues, none")
        for res_id in all_residues:
            sel = _residue_selection(res_id, has_chains)
            lines.append(f"select interacting_residues, interacting_residues or ({sel})")
        
        lines.extend([
            "select interacting_residues, interacting_residues and not ligand",
            "show sticks, interacting_residues",
            "color cyan, interacting_residues and elem C",
            "label interacting_residues and name CA, resn + resi",
            "set label_size, 18",
            "set label_font_id, 7",
            "set label_color, black",
            "",
        ])
    
    # Generate interaction visualizations
    lines.extend(_generate_interaction_lines(results, "", has_chains))
    
    return lines


def _generate_interaction_lines(results: Dict, prefix: str, has_chains: bool = True) -> List[str]:
    """Generate PyMOL commands for interaction visualization.
    
    Args:
        results: Dictionary of interaction results
        prefix: Prefix for object names
        has_chains: If False, omit chain from selections (for docked files)
    """
    lines = []
    pi_counter = 0
    
    for itype, interactions in results.items():
        if not interactions:
            continue
        
        color = INTERACTION_COLORS.get(itype, 'grey')
        lines.append(f"# {itype}")
        
        for idx, inter in enumerate(interactions, 1):
            safe_type = itype.replace(' ', '_').replace('-', '_').replace('π', 'pi')
            obj_name = f"{prefix}_{safe_type}_{idx}" if prefix else f"{safe_type}_{idx}"
            
            chain, res_num = _parse_residue_id(inter.protein_residue, has_chains)
            
            # Handle special interaction types
            if itype == "π-π Stacking":
                pi_counter += 1
                lines.extend(_generate_pi_stacking(inter, obj_name, prefix, pi_counter, color))
            elif itype == "Cation-π":
                # Ligand cation -> Protein aromatic ring (protein needs pseudocenter)
                pi_counter += 1
                lines.extend(_generate_cation_pi(inter, obj_name, prefix, pi_counter, color, has_chains))
            elif itype == "π-Cation":
                # Ligand aromatic ring -> Protein cation (ligand needs pseudocenter)
                pi_counter += 1
                lines.extend(_generate_pi_cation(inter, obj_name, prefix, pi_counter, color, has_chains))
            elif itype == "Water Bridges":
                lines.extend(_generate_water_bridge(inter, obj_name, chain, res_num, has_chains))
            elif itype == "XWH Bridges":
                lines.extend(_generate_xwh_bridge(inter, obj_name, chain, res_num, has_chains))
            elif itype == "Metal Coordination":
                lines.extend(_generate_metal_coord(inter, obj_name, has_chains))
            else:
                lines.extend(_generate_standard_interaction(inter, obj_name, chain, res_num, color, has_chains, int_type=itype))
        
        lines.append("")
    
    return lines


def _residue_selection(res_id: str, has_chains: bool = True) -> str:
    """Generate PyMOL selection for a residue ID.
    
    Args:
        res_id: Residue ID like 'A:ARG308' or 'ARG308'
        has_chains: If False, omit chain from selection (for docked files)
    """
    if ':' in res_id:
        chain, res_part = res_id.split(':')
        res_num = ''.join(c for c in res_part if c.isdigit() or c == '-')
        if has_chains:
            return f"chain {chain} and resi {res_num} and polymer.protein"
        else:
            return f"resi {res_num} and polymer.protein"
    else:
        res_num = ''.join(c for c in res_id if c.isdigit() or c == '-')
        return f"resi {res_num} and polymer.protein"


def _parse_residue_id(res_id: str, has_chains: bool = True) -> Tuple[str, str]:
    """Parse residue ID into chain and residue number.
    
    Args:
        res_id: Residue ID like 'A:ARG308' or 'ARG308'
        has_chains: If False, return empty chain (for docked files)
    """
    if ':' in res_id:
        chain, res_part = res_id.split(':')
        res_num = ''.join(c for c in res_part if c.isdigit() or c == '-')
        return (chain, res_num) if has_chains else ("", res_num)
    else:
        res_num = ''.join(c for c in res_id if c.isdigit() or c == '-')
        return "", res_num


def _atom_selection(atom, chain: str = "", res_num: str = "", has_chains: bool = True) -> str:
    """Generate atom selection string.
    
    Args:
        atom: Atom object with res_name, res_seq, name, chain_id
        chain: Fallback chain ID if atom doesn't have one
        res_num: Fallback residue number
        has_chains: If True, include chain in selection (for proper PDB files)
                    If False, omit chain (for docked files without chains)
    
    This handles:
    - Multiple identical ligands on different chains (when has_chains=True)
    - Docked files without chain IDs (when has_chains=False)
    """
    from .constants import STANDARD_AMINO_ACIDS
    
    # Check if this is a ligand atom (non-standard residue)
    is_ligand = hasattr(atom, 'res_name') and atom.res_name not in STANDARD_AMINO_ACIDS \
                and atom.res_name not in ('HOH', 'WAT')
    
    if is_ligand:
        # LIGAND: Always use OR-fallback when has_chains=True.
        # This handles docked ligands where the chain ID in the raw PDB is blank
        # but the parser defaulted it to 'A'.
        if has_chains and hasattr(atom, 'chain_id') and atom.chain_id and atom.chain_id.strip():
            sel_with = f"chain {atom.chain_id} and resn {atom.res_name} and resi {atom.res_seq} and name {atom.name}"
            sel_without = f"resn {atom.res_name} and resi {atom.res_seq} and name {atom.name}"
            return f"({sel_with}) or ({sel_without})"
        else:
            return f"resn {atom.res_name} and resi {atom.res_seq} and name {atom.name}"
    else:
        # PROTEIN: Use chain if available and has_chains=True
        if has_chains and hasattr(atom, 'chain_id') and atom.chain_id and atom.chain_id.strip():
            return f"chain {atom.chain_id} and resn {atom.res_name} and resi {atom.res_seq} and name {atom.name}"
        elif has_chains and chain:
            return f"chain {chain} and resi {res_num or atom.res_seq} and name {atom.name}"
        else:
            return f"resi {atom.res_seq} and name {atom.name}"


def _generate_pi_stacking(inter: Interaction, obj_name: str, 
                          prefix: str, counter: int, color: str) -> List[str]:
    """Generate π-π stacking visualization."""
    lines = []
    if inter.protein_atoms and inter.ligand_atoms:
        import numpy as np
        prot_c = np.mean([a.coords for a in inter.protein_atoms], axis=0)
        lig_c = np.mean([a.coords for a in inter.ligand_atoms], axis=0)
        
        pp = f"{prefix}_pring_{counter}" if prefix else f"pring_{counter}"
        lp = f"{prefix}_lring_{counter}" if prefix else f"lring_{counter}"
        
        # Get dash settings (solid line)
        dash_gap, dash_len = INTERACTION_DASH.get('π-π Stacking', (0, 0.5))
        
        lines.extend([
            f"pseudoatom {pp}, pos=[{prot_c[0]:.3f}, {prot_c[1]:.3f}, {prot_c[2]:.3f}]",
            f"pseudoatom {lp}, pos=[{lig_c[0]:.3f}, {lig_c[1]:.3f}, {lig_c[2]:.3f}]",
            f"show spheres, {pp} {lp}",
            f"set sphere_scale, 0.15, {pp} {lp}",
            f"color yellow, {pp} {lp}",
            f"distance {obj_name}, {pp}, {lp}",
            f"color {color}, {obj_name}",
            f"set dash_gap, {dash_gap}, {obj_name}",
            f"set dash_length, {dash_len}, {obj_name}",
        ])
    return lines


def _generate_cation_pi(inter: Interaction, obj_name: str, 
                        prefix: str, counter: int, color: str,
                        has_chains: bool = True) -> List[str]:
    """Generate Cation-π visualization (ligand cation → protein aromatic ring).
    
    Protein has aromatic ring (needs pseudocenter at ring centroid).
    Ligand has cation (use first atom - typically N or charged center).
    """
    lines = []
    if inter.protein_atoms and inter.ligand_atoms:
        import numpy as np
        # Protein aromatic ring - calculate centroid
        prot_c = np.mean([a.coords for a in inter.protein_atoms], axis=0)
        # Ligand cation - use first atom (the charged atom)
        lig_atom = inter.ligand_atoms[0]
        
        pp = f"{prefix}_pring_{counter}" if prefix else f"pring_{counter}"
        lig_sel = _atom_selection(lig_atom, has_chains=has_chains)
        
        # Get dash settings (solid line)
        dash_gap, dash_len = INTERACTION_DASH.get('Cation-π', (0, 0.5))
        
        lines.extend([
            f"pseudoatom {pp}, pos=[{prot_c[0]:.3f}, {prot_c[1]:.3f}, {prot_c[2]:.3f}]",
            f"show spheres, {pp}",
            f"set sphere_scale, 0.15, {pp}",
            f"color orange, {pp}",
            f"distance {obj_name}, {pp}, ({lig_sel})",
            f"color {color}, {obj_name}",
            f"set dash_gap, {dash_gap}, {obj_name}",
            f"set dash_length, {dash_len}, {obj_name}",
        ])
    return lines


def _generate_pi_cation(inter: Interaction, obj_name: str, 
                        prefix: str, counter: int, color: str,
                        has_chains: bool = True) -> List[str]:
    """Generate π-Cation visualization (ligand aromatic ring → protein cation).
    
    Ligand has aromatic ring (needs pseudocenter at ring centroid).
    Protein has cation (use first atom - typically NZ for LYS, NH1/NH2 for ARG).
    """
    lines = []
    if inter.protein_atoms and inter.ligand_atoms:
        import numpy as np
        # Ligand aromatic ring - calculate centroid
        lig_c = np.mean([a.coords for a in inter.ligand_atoms], axis=0)
        # Protein cation - use first atom
        prot_atom = inter.protein_atoms[0]
        
        lp = f"{prefix}_lring_{counter}" if prefix else f"lring_{counter}"
        prot_sel = _atom_selection(prot_atom, has_chains=has_chains)
        
        # Get dash settings (solid line)
        dash_gap, dash_len = INTERACTION_DASH.get('π-Cation', (0, 0.5))
        
        lines.extend([
            f"pseudoatom {lp}, pos=[{lig_c[0]:.3f}, {lig_c[1]:.3f}, {lig_c[2]:.3f}]",
            f"show spheres, {lp}",
            f"set sphere_scale, 0.15, {lp}",
            f"color chocolate, {lp}",
            f"distance {obj_name}, ({prot_sel}), {lp}",
            f"color {color}, {obj_name}",
            f"set dash_gap, {dash_gap}, {obj_name}",
            f"set dash_length, {dash_len}, {obj_name}",
        ])
    return lines


def _generate_water_bridge(inter: Interaction, obj_name: str,
                            chain: str, res_num: str, has_chains: bool = True) -> List[str]:
    """Generate water bridge visualization.
    
    Water bridges are shown as two dashed lines:
    - Protein atom → Water molecule
    - Water molecule → Ligand atom
    
    Uses water atom coordinates directly via pseudoatom to avoid selecting
    wrong water molecules in multi-chain structures with duplicate waters.
    """
    lines = []
    
    # Water bridge requires: protein_atoms[0]=protein, protein_atoms[1]=water, ligand_atoms[0]=ligand
    if len(inter.protein_atoms) < 2 or not inter.ligand_atoms:
        return lines
    
    prot_atom = inter.protein_atoms[0]
    water_atom = inter.protein_atoms[1]
    lig_atom = inter.ligand_atoms[0]
    
    # Get water atom coordinates for direct positioning
    water_coords = water_atom.coords
    water_res_seq = water_atom.res_seq
    
    prot_sel = _atom_selection(prot_atom, chain, res_num, has_chains)
    lig_sel = _atom_selection(lig_atom, has_chains=has_chains)
    
    # Use marine color to match 2D diagram
    color = 'marine'
    
    # Get dash settings for water bridges (dashed line)
    dash_gap, dash_len = INTERACTION_DASH.get('Water Bridges', (0.15, 0.20))
    
    # Create a pseudoatom at the exact water position to avoid selecting wrong waters
    water_pseudo = f"{obj_name}_water"
    
    lines.extend([
        f"# Water bridge via HOH {water_res_seq}",
        f"pseudoatom {water_pseudo}, pos=[{water_coords[0]:.3f}, {water_coords[1]:.3f}, {water_coords[2]:.3f}]",
        f"show spheres, {water_pseudo}",
        f"set sphere_scale, 0.25, {water_pseudo}",
        f"color {color}, {water_pseudo}",
        f"distance {obj_name}_pw, ({prot_sel}), {water_pseudo}",
        f"distance {obj_name}_wl, {water_pseudo}, ({lig_sel})",
        f"color {color}, {obj_name}_pw {obj_name}_wl",
        f"set dash_gap, {dash_gap}, {obj_name}_pw {obj_name}_wl",
        f"set dash_length, {dash_len}, {obj_name}_pw {obj_name}_wl",
    ])
    return lines


def _generate_xwh_bridge(inter: Interaction, obj_name: str,
                          chain: str, res_num: str, has_chains: bool = True) -> List[str]:
    """Generate XWH (halogen-water-hydrogen) bridge visualization.
    
    XWH bridges are shown as two dashed lines:
    - Halogen atom (ligand) → Water molecule  (X-bond leg)
    - Water molecule → Protein atom           (H-bond leg)
    
    Uses water atom coordinates directly via pseudoatom to avoid selecting
    wrong water molecules in multi-chain structures with duplicate waters.
    """
    lines = []
    
    # XWH bridge requires: protein_atoms[0]=protein, protein_atoms[1]=water, ligand_atoms[0]=halogen
    if len(inter.protein_atoms) < 2 or not inter.ligand_atoms:
        return lines
    
    prot_atom = inter.protein_atoms[0]
    water_atom = inter.protein_atoms[1]
    lig_atom = inter.ligand_atoms[0]
    
    # Get water atom coordinates for direct positioning
    water_coords = water_atom.coords
    water_res_seq = water_atom.res_seq
    
    prot_sel = _atom_selection(prot_atom, chain, res_num, has_chains)
    lig_sel = _atom_selection(lig_atom, has_chains=has_chains)
    
    # Use slate color to match 2D diagram (Medium Slate Blue)
    color = 'slate'
    
    # Get dash settings for XWH bridges (dashed line)
    dash_gap, dash_len = INTERACTION_DASH.get('XWH Bridges', (0.15, 0.20))
    
    # Create a pseudoatom at the exact water position to avoid selecting wrong waters
    water_pseudo = f"{obj_name}_water"
    
    halogen = inter.extra_info.get('halogen', 'X') if inter.extra_info else 'X'
    lines.extend([
        f"# XWH bridge: {halogen}···HOH {water_res_seq}···{prot_atom.res_name}{prot_atom.res_seq} {prot_atom.name}",
        f"pseudoatom {water_pseudo}, pos=[{water_coords[0]:.3f}, {water_coords[1]:.3f}, {water_coords[2]:.3f}]",
        f"show spheres, {water_pseudo}",
        f"set sphere_scale, 0.25, {water_pseudo}",
        f"color {color}, {water_pseudo}",
        f"distance {obj_name}_pw, ({prot_sel}), {water_pseudo}",
        f"distance {obj_name}_wl, {water_pseudo}, ({lig_sel})",
        f"color {color}, {obj_name}_pw {obj_name}_wl",
        f"set dash_gap, {dash_gap}, {obj_name}_pw {obj_name}_wl",
        f"set dash_length, {dash_len}, {obj_name}_pw {obj_name}_wl",
    ])
    return lines


def _generate_metal_coord(inter: Interaction, obj_name: str, has_chains: bool = True) -> List[str]:
    """Generate metal coordination visualization.
    
    Shows metal coordination as a dashed line without thick stick representation
    to distinguish it from covalent bonds.
    """
    lines = []
    if not inter.extra_info:
        return lines
    
    metal_name = inter.extra_info.get('metal', '')
    metal_id = inter.extra_info.get('metal_id', '')
    source = inter.extra_info.get('source', 'protein')
    
    # Parse metal ID for selection
    if metal_id and ':' in metal_id and has_chains:
        metal_chain, metal_res = metal_id.split(':')
        metal_resnum = ''.join(c for c in metal_res if c.isdigit())
        metal_sel = f"chain {metal_chain} and resn {metal_name} and resi {metal_resnum}"
    else:
        metal_sel = f"resn {metal_name}"
    
    metal_color = METAL_COLORS.get(metal_name.upper(), 'magenta')
    
    # Bridging metals have both protein_atoms and ligand_atoms populated.
    # We need to draw distance lines for BOTH sides: metal→protein AND metal→ligand.
    metal_bridged = inter.extra_info.get('metal_bridged', False)

    # Collect all (coord_sel, obj_suffix) pairs to draw
    coord_pairs = []  # list of (selection_string, obj_name_suffix)

    if source == 'water':
        water_atom = inter.extra_info.get('water_atom')
        if water_atom:
            coord_sel = f"resn HOH and resi {water_atom.res_seq} and name O"
            lines.extend([
                f"show spheres, {coord_sel}",
                f"set sphere_scale, 0.15, {coord_sel}",
                f"color red, {coord_sel}",
            ])
            coord_pairs.append((coord_sel, obj_name))
    elif metal_bridged:
        # Bridging: draw to protein atom AND ligand atom
        if inter.protein_atoms:
            prot_sel = _atom_selection(inter.protein_atoms[0], has_chains=has_chains)
            coord_pairs.append((prot_sel, f"{obj_name}_prot"))
        if inter.ligand_atoms:
            lig_sel = _atom_selection(inter.ligand_atoms[0], has_chains=has_chains)
            coord_pairs.append((lig_sel, f"{obj_name}_lig"))
    elif source in ('protein', 'protein_backbone'):
        if inter.protein_atoms:
            coord_sel = _atom_selection(inter.protein_atoms[0], has_chains=has_chains)
            coord_pairs.append((coord_sel, obj_name))
        else:
            return lines
    elif source == 'ligand' or source == 'bridging':
        if inter.ligand_atoms:
            coord_sel = _atom_selection(inter.ligand_atoms[0], has_chains=has_chains)
            coord_pairs.append((coord_sel, obj_name))
        else:
            return lines
    else:
        return lines

    if not coord_pairs:
        return lines

    # Get dash settings - use dashed line to distinguish from covalent bonds
    dash_gap, dash_len = (0.2, 0.15)  # Dashed style

    lines.extend([
        f"# Remove ALL bonds from metal atom to prevent covalent appearance",
        f"unbond ({metal_sel}), *",
        f"# Show metal as sphere only",
        f"show spheres, ({metal_sel})",
        f"set sphere_scale, 0.3, ({metal_sel})",
        f"color {metal_color}, ({metal_sel})",
        f"hide sticks, ({metal_sel})",
        f"hide lines, ({metal_sel})",
    ])

    for coord_sel, dist_obj in coord_pairs:
        lines.extend([
            f"# Create thin dashed line for coordination bond",
            f"distance {dist_obj}, ({metal_sel}), ({coord_sel})",
            f"color {metal_color}, {dist_obj}",
            f"set dash_gap, {dash_gap}, {dist_obj}",
            f"set dash_length, {dash_len}, {dist_obj}",
            f"set dash_width, 0.5, {dist_obj}",
            f"set dash_radius, 0.05, {dist_obj}",
            f"set label_size, 18, {dist_obj}",
            f"set label_color, black, {dist_obj}",
        ])

    return lines


def _generate_standard_interaction(inter: Interaction, obj_name: str,
                                    chain: str, res_num: str, color: str, 
                                    has_chains: bool = True,
                                    int_type: str = "") -> List[str]:
    """Generate standard interaction visualization with proper line styles.
    
    Line styles match 2D diagram:
    - Hydrogen Bonds: solid with arrow (in 2D), solid in PyMOL
    - Salt Bridges: solid
    - Hydrophobic: dashed
    - Halogen Bonds: dashed
    """
    lines = []
    
    if inter.protein_atoms:
        prot_atom_name = inter.protein_atoms[0].name
    else:
        prot_atom_name = "CA"
    
    if not inter.ligand_atoms:
        return lines
    
    lig_atom = inter.ligand_atoms[0]
    
    if chain:
        prot_sel = f"chain {chain} and resi {res_num} and name {prot_atom_name}"
    else:
        prot_sel = f"resi {res_num} and name {prot_atom_name}"
    
    lig_sel = _atom_selection(lig_atom, has_chains=has_chains)
    
    lines.extend([
        f"distance {obj_name}, ({prot_sel}), ({lig_sel})",
        f"color {color}, {obj_name}",
        f"set label_size, 18, {obj_name}",
        f"set label_color, black, {obj_name}",
    ])
    
    # Set dash style based on interaction type to match 2D diagram
    # Solid lines: Hydrogen Bonds, Salt Bridges
    # Dashed lines: Hydrophobic, Halogen Bonds
    if int_type in ('Hydrogen Bonds', 'Salt Bridges'):
        # Solid line (no dash)
        lines.append(f"set dash_gap, 0, {obj_name}")
        lines.append(f"set dash_length, 0.5, {obj_name}")
    else:
        # Dashed line for hydrophobic, halogen bonds, etc.
        dash_settings = INTERACTION_DASH.get(int_type, (0.15, 0.25))
        lines.append(f"set dash_gap, {dash_settings[0]}, {obj_name}")
        lines.append(f"set dash_length, {dash_settings[1]}, {obj_name}")
    
    return lines


# ============================================================================
# SCRIPT GENERATION
# ============================================================================

def save_script_only(pdb_file: str, 
                     results: Dict,
                     ligand_name: str = None,
                     output_script: str = "interactions.pml",
                     ligand_info: dict = None) -> bool:
    """
    Save PyMOL script without executing.
    
    Args:
        pdb_file: Path to PDB file
        results: Dictionary of interactions
        ligand_name: Optional ligand name
        output_script: Output script file path
        ligand_info: Optional ligand info dictionary
        
    Returns:
        True if script was saved successfully
    """
    script = generate_pymol_script(
        pdb_file, results, ligand_name,
        output_script.replace('.pml', '.pse'),
        ligand_info
    )
    
    with open(output_script, 'w') as f:
        f.write(script)
    
    print(f"\n✓ PyMOL script saved: {output_script}")
    print(f"  Run with: pymol {output_script}")
    
    return True
